package com.new_ton.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.new_ton.domain.dto.PrintTestReportDto;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Paths;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

@RequiredArgsConstructor
@Log4j2
@Service
public class ProductIntroductionCardPdfServiceImpl implements ProductIntroductionCardPdfService {

    private final PrintDocumentService printDocumentService;


    public boolean productIntroductionCard(PrintTestReportDto dto) {
        try {
            StringBuilder mainDirectory = new StringBuilder();
            mainDirectory.append("C:/NewTon");
            if (!Files.exists(Paths.get(mainDirectory.toString()))) {
                log.info("Create directory " + mainDirectory);
                Files.createDirectory(Paths.get(mainDirectory.toString()));
            }

            mainDirectory.append("/ProductIntroductionCardLabels");
            if (!Files.exists(Paths.get(mainDirectory.toString()))) {
                Files.createDirectory(Paths.get(mainDirectory.toString()));
                log.info("Create directory " + mainDirectory);
            }

            Date date = Calendar.getInstance().getTime();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String currentDate = dateFormat.format(date);
            mainDirectory.append("/").append(currentDate);
            if (!Files.exists(Paths.get(mainDirectory.toString()))) {
                Files.createDirectory(Paths.get(mainDirectory.toString()));
                log.info("Create directory " + mainDirectory);
            }

            log.info("Start create document " + mainDirectory);
            mainDirectory.append("/ProductIntroductionCard_id_prod_").append(dto.getIdProd()).append(".pdf");
            BaseColor color = new BaseColor(250, 193, 148);
            URL FONT = this.getClass().getClassLoader().getResource("fonts/RobotoCondensed-Regular.ttf");
            BaseFont baseFont = BaseFont.createFont(FONT.toString(), "Identity-H", true);
            Font font1 = new Font(baseFont, 13.0F, 0);
            Font font2 = new Font(baseFont, 14.0F, 1);
            URL imageFile = this.getClass().getClassLoader().getResource("image/new_ton.png");
            Image image = Image.getInstance(imageFile.toString());
            PdfPTable table = new PdfPTable(new float[]{1.0F, 0.9F, 0.5F, 0.7F, 1.5F, 1.6F, 1.2F});
            table.setWidthPercentage(95.0F);
            PdfPCell cell = new PdfPCell();
            cell.setBorderWidthTop(1.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setImage(image);
            cell.setHorizontalAlignment(1);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Карта введення продукції", font2));
            cell.setColspan(4);
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(1.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("№ протоколу", font1));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(1.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setFixedHeight(35.0F);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(String.valueOf(dto.getNumbprot()), font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(1.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Дата \n вироб-ва", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(28.0F);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Найменування продукту", font2));
            cell.setColspan(4);
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Параметр контролю", font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Відмітка", font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getDatemade(), font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getNameprod(), font2));
            cell.setColspan(4);
            cell.setRowspan(4);
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Тип клапана", font1));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getValveTypeDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setFixedHeight(35.0F);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("№ партії", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Тип розп. голівки", font1));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getSprayHeadTypeDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getNumbpart(), font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setRowspan(2);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Відповідність кольору, ΔЕ", font1));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getColorDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Ступінь глянцю", font1));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getDegreeOfGlossDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Вязкість, с ", font1));
            cell.setBackgroundColor(color);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Щільність", font1));
            cell.setBackgroundColor(color);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Розведення", font1));
            cell.setBackgroundColor(color);
            cell.setColspan(2);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Кількість газу, г", font1));
            cell.setBackgroundColor(color);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Нанесення", font1));
            cell.setBackgroundColor(color);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("відповідає", font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getViscosityDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getDensityDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            String dilutionFull = dto.getDulitionDto().getResult();
            int index = dilutionFull.indexOf("-");
            String dilution1 = dilutionFull.substring(0, index);
            String dilution2 = dilutionFull.substring(index + 1);
            cell = new PdfPCell(new Phrase(dilution1, font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dilution2, font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getQuantityDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Зовнішній вигляд покриття", font1));
            cell.setBackgroundColor(color);
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getAppearanceDto().getResult(), font2));
            cell.setHorizontalAlignment(1);
            cell.setVerticalAlignment(5);
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setFixedHeight(35.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(""));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setColspan(3);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(""));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setColspan(2);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Час висихання", font1));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setBackgroundColor(color);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("          хв.", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Посада", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setBackgroundColor(color);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setColspan(3);
            cell.setFixedHeight(20.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Підпис", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setBackgroundColor(color);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setColspan(2);
            cell.setFixedHeight(20.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("П.І.П", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(0.5F);
            cell.setColspan(2);
            cell.setBackgroundColor(color);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setFixedHeight(20.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Начальник лабораторії з \n контролю виробництва ", font2));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(1.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(1.5F);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setColspan(3);
            cell.setFixedHeight(50.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(""));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(0.5F);
            cell.setBorderWidthBottom(1.5F);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setColspan(2);
            cell.setFixedHeight(50.0F);
            table.addCell(cell);
            cell = new PdfPCell(new Phrase(dto.getLabfio(), font1));
            cell.setBorderWidthTop(0.5F);
            cell.setBorderWidthLeft(0.5F);
            cell.setBorderWidthRight(1.5F);
            cell.setBorderWidthBottom(1.5F);
            cell.setColspan(2);
            cell.setVerticalAlignment(5);
            cell.setHorizontalAlignment(1);
            cell.setFixedHeight(50.0F);
            table.addCell(cell);
            Document document = new Document();
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, byteArrayOutputStream);
            document.open();
            document.add(table);
            document.close();

            try {
                FileOutputStream fileOutputStream = new FileOutputStream(mainDirectory.toString());

                boolean var22;
                try {
                    fileOutputStream.write(byteArrayOutputStream.toByteArray());
                    var22 = printDocumentService.printDocument(mainDirectory.toString());
                } catch (Throwable var25) {
                    try {
                        fileOutputStream.close();
                    } catch (Throwable var24) {
                        var25.addSuppressed(var24);
                    }

                    throw var25;
                }

                fileOutputStream.close();
                return var22;
            } catch (Exception e) {
                log.error("Error save document : {}, {}", ExceptionUtils.getMessage(e), ExceptionUtils.getMessage(e.getCause()));
            }
        } catch (Exception e) {
            log.error("Error product introduction card : {}, {}", ExceptionUtils.getMessage(e), ExceptionUtils.getMessage(e.getCause()));
        }

        return false;
    }
}
